### ISSUE TITLE
Symbolic links home for sui-base

### ISSUE THREAD

**Issue by FrankC01** [ChainMovers/suibase#10]
### Discussed in https://github.com/sui-base/sui-base/discussions/7

<div type='discussions-op-text'>

<sup>Originally posted by **FrankC01** March  6, 2023</sup>
Currently scripts go to `.local/bin/`
Should they go in `.local/bin/sui-base`?

</div>

**Comment by mario4tier** [comment]
I think .local/bin is the right place. 

2 weak reasons against creating a sub-directory (on short term).

(1) May be you have in mind minimizing chance of name collision? Considering that everything put in a sub-directory would also end-up on the same $PATH, then any name contention could be obscure (at exec time) instead of getting a chance being observe at installation time (symlink fail) when in same directory.

This is how it fails right now on name clash:
```~/sui-base$ ./install
Starting installation of sui-base...
ln: failed to create symbolic link '/home/olet/.local/bin/lsui': File exists
   Symlink added: /home/olet/.local/bin/lsui -> /home/olet/sui-base/scripts/lsui
./install: line 84: /home/olet/.local/bin/lsui: Permission denied
setup of lsui symlink failed
```

(2) One drawback , a sub-directory would require to support modifying $PATH on *all* platform... a bit of a challenge out of the gate compare to .local/bin being (it seems) common enough on many user setup.

===

The only pros coming to mind for a sub-directory would be some clarity if someone have a "peek" to find what is related to sui-base. Do you see something else?
