### ISSUE TITLE
Keytool does not generate private key

### ISSUE THREAD

**Issue by porkbrain** [ChainMovers/suibase#112]
```
lsui --version
sui 1.32.1-624300d58ded
```

Using `$ lsui keytool generate ed25519` does not create any `.key` file as advertized in the command description. Replacing `lsui` with `sui` generates the file.

**Comment by mario4tier** [comment]
Thanks for reporting this. 

In short: 
   (1) I will fix it in the coming days (so it is consistent with "sui").
   (2) In meantime, you will find the .key files in ~/suibase/workdirs/localnet/logs/sui.log

Details on the fix (optional read)
========================
A long time ago the sui commands were creating (by default) log files in the current directory. This was very "polluting", so I decided to always call the sui binary after a 'cd' to that sui.log directory (so all logs end up cleanly in one place).
Since that time, they fix the way the logs work (now always disabled by default), so it is no longer needed to always 'cd' to sui.log
I will look into fixing this by removing the 'cd'

This is a quick fix, just need a bit more time to test.



    On Thursday, September 5, 2024 at 09:12:42 AM EDT, porkbrain ***@***.***> wrote:  
 
 

lsui --version
sui 1.32.1-624300d58ded

Using $ lsui keytool generate ed25519 does not create any .key file as advertized in the command description. Replacing lsui with sui generates the file.

**Comment by mario4tier** [comment]
The fix is now merge.

Update your setup with "~/suibase/update"

Thanks.

**Comment by porkbrain** [comment]
Thanks for the rapid fix and the explanation!
