### ISSUE TITLE
localnet stop/status still showing running

### ISSUE THREAD

**Issue by FrankC01** [ChainMovers/suibase#79]
```bash
$ localnet stop
Stopping localnet (process pid 4202)
...............
Error: Sui process pid=4593 still running. Try again, or stop (kill) the sui process yourself before proceeding.

$ localnet status
localnet STOPPED
---
localnet process : STILL RUNNING (pid 4593)
multi-link RPC   :  (  )
---
client version: sui 1.9.1-8c2cf85
asui selection: [ localnet ]
```

**Comment by mario4tier** [comment]
Thanks for reporting this.

Bug in suibase is now fix.

Details
=======
get_process_pid() was returning the wrong PID for the "sui" process on MacOS.
It was instead likely returning the PID of the "suibase-daemon" process.

Two things are part of this fix:
  - On MacOS, look for an *exact* match of the process name (instead of allowing for substring).
  - Include the grepping on the fullpath to make sure targeting the right binary.
  
Long Term Fix
=============
This first fix is making things significantly more robust. But there is still some unlikely race condition possible. Examples:
- User doing a "sui" command at same time as doing "stop".
- User doing competing start/stop at "same time" from two different terminal.

These should be fix with a mechanism to prevent concurrent execution of the Suibase scripts (e.g. block until other script execution completes).

**Comment by mario4tier** [comment]
With this fix, command done at same time (e.g. from two terminals) for same workdir will be executed sequentially, which is more safe.

Command for different workdirs can still be executed in parallel.

(the "status" command do not modify anything, so it does not need the mutex and is allowed to be done concurrently)
